# Generated by Django 3.2.8 on 2021-10-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='image2',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='image3',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='image4',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='image5',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
